drop table excise_locations cascade constraints;
drop table excise_parties cascade constraints;
drop table excise_party_identifiers cascade constraints;
drop table excise_events cascade constraints;
drop table excise_event_parties cascade constraints;
drop table excise_warehouses cascade constraints;
drop table excise_event_warehouses cascade constraints;
drop table excise_movements cascade constraints;
drop table excise_movement_references cascade constraints;
drop table excise_movement_seals cascade constraints;
drop table excise_items cascade constraints;
drop table excise_item_strength cascade constraints;
drop table excise_item_packaging cascade constraints;
drop table excise_item_relief cascade constraints;
drop table excise_tax_calculations cascade constraints;
drop table excise_tax_lines cascade constraints;
drop table excise_evidence cascade constraints;
-- create tables

create table excise_locations (
    location_id      number generated by default on null as identity
                     constraint excise_locations_location_id_pk primary key,
    name             varchar2(255 char),
    address_line1    varchar2(255 char),
    address_line2    varchar2(255 char),
    city             varchar2(255 char),
    postal_code      varchar2(20 char),
    country_code     varchar2(2 char),
    latitude         number(9,6),
    longitude        number(9,6),
    created          date not null,
    created_by       varchar2(255 char) not null,
    updated          date not null,
    updated_by       varchar2(255 char) not null
);



create table excise_parties (
    party_id       number generated by default on null as identity
                   constraint excise_parties_party_id_pk primary key,
    location_id    number                   constraint excise_parties_location_id_fk
                   references excise_locations,
    party_type     varchar2(255 char) not null constraint excise_parties_party_type_ck
                   check (party_type in ('PERSON','ORGANIZATION')),
    name           varchar2(255 char) not null,
    email          varchar2(255 char),
    phone          varchar2(255 char),
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);

-- table index
create index excise_parties_i1 on excise_parties (location_id);

create index excise_parties_i2 on excise_parties (name);


create table excise_party_identifiers (
    party_identifier_id    number generated by default on null as identity
                           constraint excise_party_identifiers_party_identifier_id_pk primary key,
    party_id               number                           constraint excise_party_identifiers_party_id_fk
                           references excise_parties,
    id_type                varchar2(255 char) not null constraint excise_party_identifiers_id_type_ck
                           check (id_type in ('VAT','EXCISE_REGISTRATION','WAREHOUSE_APPROVAL','EORI','COMPANY_NUMBER','NATIONAL_ID','OTHER')),
    id_value               varchar2(255 char) not null,
    issuing_country        varchar2(2 char),
    valid_from             date,
    valid_to               date,
    created                date not null,
    created_by             varchar2(255 char) not null,
    updated                date not null,
    updated_by             varchar2(255 char) not null
);

-- table index
create index excise_party_identifiers_i1 on excise_party_identifiers (party_id);



create table excise_events (
    event_id                  number generated by default on null as identity
                              constraint excise_events_event_id_pk primary key,
    duty_point_location_id    number                              constraint excise_events_duty_point_location_id_fk
                              references excise_locations,
    event_type                varchar2(255 char) not null constraint excise_events_event_type_ck
                              check (event_type in ('PRODUCED','RECEIVED','MOVED_UNDER_SUSPENSION','IMPORTED','EXPORTED','RELEASED_FOR_CONSUMPTION','DESTROYED','LOSS_OR_SHORTAGE','RETURNED','ADJUSTMENT')),
    event_ts                  timestamp not null,
    country_code              varchar2(2 char) not null,
    region                    varchar2(255 char),
    authority                 varchar2(255 char),
    duty_status               varchar2(255 char) not null constraint excise_events_duty_status_ck
                              check (duty_status in ('DUTY_SUSPENDED','DUTY_PAID','EXEMPT','RELIEF_CLAIMED')),
    duty_point_type           varchar2(30 char),
    duty_point_ref            varchar2(255 char),
    extensions                clob,
    source_system             varchar2(255 char),
    version                   varchar2(4000 char) default on null '1' not null,
    created                   date not null,
    created_by                varchar2(255 char) not null,
    updated                   date not null,
    updated_by                varchar2(255 char) not null
);

-- table index
create index excise_events_i1 on excise_events (duty_point_location_id);



create table excise_event_parties (
    event_party_id    number generated by default on null as identity
                      constraint excise_event_parties_event_party_id_pk primary key,
    event_id          number                      constraint excise_event_parties_event_id_fk
                      references excise_events,
    pary_id           number                      constraint excise_event_parties_pary_id_fk
                      references excise_parties,
    role              varchar2(255 char) not null constraint excise_event_parties_role_ck
                      check (role in ('OWNER','CONSIGNOR','CONSIGNEE','WAREHOUSE_KEEPER','TRANSPORTER','AGENT')),
    created           date not null,
    created_by        varchar2(255 char) not null,
    updated           date not null,
    updated_by        varchar2(255 char) not null
);

-- table index
create index excise_event_parties_i1 on excise_event_parties (event_id);

create index excise_event_parties_i2 on excise_event_parties (pary_id);



create table excise_warehouses (
    warehouse_id         number generated by default on null as identity
                         constraint excise_warehouses_warehouse_id_pk primary key,
    location_id          number                         constraint excise_warehouses_location_id_fk
                         references excise_locations,
    operator_party_id    number                         constraint excise_warehouses_operator_party_id_fk
                         references excise_parties,
    warehouse_code       varchar2(255 char),
    approval_number      varchar2(255 char),
    created              date not null,
    created_by           varchar2(255 char) not null,
    updated              date not null,
    updated_by           varchar2(255 char) not null
);

-- table index
create index excise_warehouses_i1 on excise_warehouses (location_id);

create index excise_warehouses_i2 on excise_warehouses (operator_party_id);

create index excise_warehouses_i3 on excise_warehouses (approval_number);


create table excise_event_warehouses (
    event_warehouse_id    number generated by default on null as identity
                          constraint excise_event_warehouses_event_warehouse_id_pk primary key,
    event_id              number                          constraint excise_event_warehouses_event_id_fk
                          references excise_events,
    warehouse_id          number                          constraint excise_event_warehouses_warehouse_id_fk
                          references excise_warehouses,
    created               date not null,
    created_by            varchar2(255 char) not null,
    updated               date not null,
    updated_by            varchar2(255 char) not null
);

-- table index
create index excise_event_warehouses_i1 on excise_event_warehouses (event_id);

create index excise_event_warehouses_i2 on excise_event_warehouses (warehouse_id);



create table excise_movements (
    movement_id                number generated by default on null as identity
                               constraint excise_movements_movement_id_pk primary key,
    event_id                   number                               constraint excise_movements_event_id_fk
                               references excise_events not null,
    dispatch_location_id       number                               constraint excise_movements_dispatch_location_id_fk
                               references excise_locations,
    destination_location_id    number                               constraint excise_movements_destination_location_id_fk
                               references excise_locations,
    movement_type              varchar2(255 char) not null constraint excise_movements_movement_type_ck
                               check (movement_type in ('SUSPENSION','DUTY_PAID','EXPORT','IMPORT','TRANSFER')),
    dispatch_ts                timestamp,
    expected_arrival_ts        timestamp,
    transport_mode             varchar2(255 char) constraint excise_movements_transport_mode_ck
                               check (transport_mode in ('ROAD','RAIL','SEA','AIR','INLAND_WATERWAY','COURIER','OTHER')),
    vehicle_id                 varchar2(255 char),
    container_id               varchar2(255 char),
    extensions                 clob default on null '{}' not null,
    created                    date not null,
    created_by                 varchar2(255 char) not null,
    updated                    date not null,
    updated_by                 varchar2(255 char) not null
);

-- table index
create index excise_movements_i1 on excise_movements (event_id);

create index excise_movements_i2 on excise_movements (dispatch_location_id);

create index excise_movements_i3 on excise_movements (destination_location_id);



create table excise_movement_references (
    movement_reference_id    number generated by default on null as identity
                             constraint excise_movement_references_movement_reference_id_pk primary key,
    movement_id              number                             constraint excise_movement_references_movement_id_fk
                             references excise_movements,
    ref_type                 varchar2(255 char) not null constraint excise_movement_references_ref_type_ck
                             check (ref_type in ('ARC','EAD','LOCAL_REFERENCE','CUSTOMS_DECLARATION','OTHER')),
    ref_value                varchar2(255 char) not null,
    created                  date not null,
    created_by               varchar2(255 char) not null,
    updated                  date not null,
    updated_by               varchar2(255 char) not null
);

-- table index
create index excise_movement_references_i1 on excise_movement_references (movement_id);



create table excise_movement_seals (
    movement_seal_id    number generated by default on null as identity
                        constraint excise_movement_seals_movement_seal_id_pk primary key,
    movement_id         number                        constraint excise_movement_seals_movement_id_fk
                        references excise_movements,
    seal_number         varchar2(255 char) not null,
    created             date not null,
    created_by          varchar2(255 char) not null,
    updated             date not null,
    updated_by          varchar2(255 char) not null
);

-- table index
create index excise_movement_seals_i1 on excise_movement_seals (movement_id);



create table excise_items (
    item_id                number generated by default on null as identity
                           constraint excise_items_item_id_pk primary key,
    event_id               number                           constraint excise_items_event_id_fk
                           references excise_events,
    category               varchar2(255 char) not null constraint excise_items_category_ck
                           check (category in ('ALCOHOL','TOBACCO','ENERGY','OTHER')),
    sub_category           varchar2(255 char),
    excise_product_code    varchar2(255 char),
    commodity_code         varchar2(255 char),
    description            varchar2(4000 char) not null,
    brand                  varchar2(255 char),
    qty_amount             number not null,
    qty_unit               varchar2(30 char) not null,
    origin_country_code    varchar2(2 char),
    customs_value          number,
    transaction_value      number,
    extensions             clob default on null '{}' not null,
    created                date not null,
    created_by             varchar2(255 char) not null,
    updated                date not null,
    updated_by             varchar2(255 char) not null
);

-- table index
create index excise_items_i1 on excise_items (event_id);

create index excise_items_i2 on excise_items (excise_product_code);


create table excise_item_strength (
    item_strength_id           number generated by default on null as identity
                               constraint excise_item_strength_item_strength_id_pk primary key,
    item_id                    number                               constraint excise_item_strength_item_id_fk
                               references excise_items,
    abv_percent                number,
    plato                      number,
    api_gravity                number,
    litres_of__pure_alcohol    number,
    created                    date not null,
    created_by                 varchar2(255 char) not null,
    updated                    date not null,
    updated_by                 varchar2(255 char) not null
);

-- table index
create index excise_item_strength_i1 on excise_item_strength (item_id);



create table excise_item_packaging (
    item_packaging_id     number generated by default on null as identity
                          constraint excise_item_packaging_item_packaging_id_pk primary key,
    item_id               number                          constraint excise_item_packaging_item_id_fk
                          references excise_items,
    package_type          varchar2(255 char) not null,
    units_per_package     number,
    package_count         number,
    net_content_amount    number,
    net_content_unit      varchar2(30 char),
    created               date not null,
    created_by            varchar2(255 char) not null,
    updated               date not null,
    updated_by            varchar2(255 char) not null
);

-- table index
create index excise_item_packaging_i1 on excise_item_packaging (item_id);



create table excise_item_relief (
    item_relief_id      number generated by default on null as identity
                        constraint excise_item_relief_item_relief_id_pk primary key,
    item_id             number                        constraint excise_item_relief_item_id_fk
                        references excise_items,
    relief_type         varchar2(255 char) not null,
    relief_reference    varchar2(255 char),
    relief_amount       number,
    extensions          clob default on null '{}' not null,
    created             date not null,
    created_by          varchar2(255 char) not null,
    updated             date not null,
    updated_by          varchar2(255 char) not null
);

-- table index
create index excise_item_relief_i1 on excise_item_relief (item_id);



create table excise_tax_calculations (
    tax_calc_id           number generated by default on null as identity
                          constraint excise_tax_calculations_tax_calc_id_pk primary key,
    event_id              number                          constraint excise_tax_calculations_event_id_fk
                          references excise_events not null,
    currency              varchar2(3 char) not null,
    calculation_method    varchar2(200 char),
    excise_duty_total     number not null,
    other_tax_total       number not null,
    grand_total           number not null,
    created               date not null,
    created_by            varchar2(255 char) not null,
    updated               date not null,
    updated_by            varchar2(255 char) not null
);

-- table index
create index excise_tax_calculations_i1 on excise_tax_calculations (event_id);



create table excise_tax_lines (
    tax_line_id           number generated by default on null as identity
                          constraint excise_tax_lines_tax_line_id_pk primary key,
    tax_calc_id           number                          constraint excise_tax_lines_tax_calc_id_fk
                          references excise_tax_calculations not null,
    item_id               number                          constraint excise_tax_lines_item_id_fk
                          references excise_items,
    tax_type              varchar2(30 char) not null constraint excise_tax_lines_tax_type_ck
                          check (tax_type in ('EXCISE_DUTY','ENVIRONMENTAL_LEVY','OTHER')),
    rate_amount           number not null,
    rate_basis            varchar2(255 char) not null,
    taxable_qty_amount    number not null,
    taxable_qty_unit      varchar2(50 char) not null,
    relief_applied        number default on null 0 not null,
    tax_amount            number not null,
    calculation_notes     varchar2(4000 char),
    extensions            clob default on null '{}' not null,
    created               date not null,
    created_by            varchar2(255 char) not null,
    updated               date not null,
    updated_by            varchar2(255 char) not null
);

-- table index
create index excise_tax_lines_i1 on excise_tax_lines (tax_calc_id);

create index excise_tax_lines_i2 on excise_tax_lines (item_id);



create table excise_evidence (
    evidence_id          number generated by default on null as identity
                         constraint excise_evidence_evidence_id_pk primary key,
    event_id             number                         constraint excise_evidence_event_id_fk
                         references excise_events,
    evidence_type        varchar2(40 char) not null constraint excise_evidence_evidence_type_ck
                         check (evidence_type in ('COMMERCIAL_INVOICE','TRANSPORT_DOCUMENT','WAREHOUSE_RECORD','LAB_CERTIFICATE','CUSTOMS_DECLARATION','LOSS_REPORT','DESTROY_CERTIFICATE','OTHER')),
    reference            varchar2(255 char) not null,
    issued_by            varchar2(255 char),
    issued_date          date,
    uri                  varchar2(4000 char),
    evidence             blob,
    evidence_filename    varchar2(255 char),
    evidence_mimetype    varchar2(255 char),
    evidence_charset     varchar2(255 char),
    evidence_lastupd     date,
    created              date not null,
    created_by           varchar2(255 char) not null,
    updated              date not null,
    updated_by           varchar2(255 char) not null
);

-- table index
create index excise_evidence_i1 on excise_evidence (event_id);



-- triggers
create or replace trigger excise_locations_biu
    before insert or update
    on excise_locations
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_locations_biu;
/


create or replace trigger excise_parties_biu
    before insert or update
    on excise_parties
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_parties_biu;
/


create or replace trigger excise_party_identifiers_biu
    before insert or update
    on excise_party_identifiers
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_party_identifiers_biu;
/


create or replace trigger excise_events_biu
    before insert or update
    on excise_events
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_events_biu;
/


create or replace trigger excise_event_parties_biu
    before insert or update
    on excise_event_parties
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_event_parties_biu;
/


create or replace trigger excise_warehouses_biu
    before insert or update
    on excise_warehouses
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_warehouses_biu;
/


create or replace trigger excise_event_warehouses_biu
    before insert or update
    on excise_event_warehouses
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_event_warehouses_biu;
/


create or replace trigger excise_movements_biu
    before insert or update
    on excise_movements
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_movements_biu;
/


create or replace trigger excise_movement_references_biu
    before insert or update
    on excise_movement_references
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_movement_references_biu;
/


create or replace trigger excise_movement_seals_biu
    before insert or update
    on excise_movement_seals
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_movement_seals_biu;
/


create or replace trigger excise_items_biu
    before insert or update
    on excise_items
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_items_biu;
/


create or replace trigger excise_item_strength_biu
    before insert or update
    on excise_item_strength
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_item_strength_biu;
/


create or replace trigger excise_item_packaging_biu
    before insert or update
    on excise_item_packaging
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_item_packaging_biu;
/


create or replace trigger excise_item_relief_biu
    before insert or update
    on excise_item_relief
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_item_relief_biu;
/


create or replace trigger excise_tax_calculations_biu
    before insert or update
    on excise_tax_calculations
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_tax_calculations_biu;
/


create or replace trigger excise_tax_lines_biu
    before insert or update
    on excise_tax_lines
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_tax_lines_biu;
/


create or replace trigger excise_evidence_biu
    before insert or update
    on excise_evidence
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end excise_evidence_biu;
/


-- Generated by Quick SQL 1.2.9 11/03/2026, 16:33:57

/*



excise_locations
  location_id /pk
  name
  address_line1 vc255
  address_line2 vc255
  city vc255
  postal_code vc20
  country_code vc2
  latitude num(9,6)
  longitude num(9,6)

excise_parties
  party_id /pk
  party_type vc255 /nn /check PERSON,ORGANIZATION
  name vc255 /nn /index
  location_id /fk excise_locations
  email
  phone vc255

excise_party_identifiers
  party_identifier_id /pk
  party_id /fk excise_parties
  id_type vc255 /nn /check 'VAT','EXCISE_REGISTRATION','WAREHOUSE_APPROVAL','EORI','COMPANY_NUMBER','NATIONAL_ID','OTHER'
  id_value vc255 /nn
  issuing_country vc2
  valid_from date
  valid_to date

excise_events
  event_id /pk
  event_type vc255 /nn /check 'PRODUCED','RECEIVED','MOVED_UNDER_SUSPENSION','IMPORTED','EXPORTED','RELEASED_FOR_CONSUMPTION','DESTROYED','LOSS_OR_SHORTAGE','RETURNED','ADJUSTMENT'
  event_ts timestamp /nn
  country_code vc2 /nn
  region vc255
  authority vc255
  duty_status vc255 /nn /check 'DUTY_SUSPENDED','DUTY_PAID','EXEMPT','RELIEF_CLAIMED'
  duty_point_type vc30
  duty_point_location_id /fk excise_locations
  duty_point_ref vc255
  extensions clob
  source_system vc255
  version /default 1 /nn

excise_event_parties
  event_party_id /pk
  event_id /fk excise_events
  role vc255 /nn /check 'OWNER','CONSIGNOR','CONSIGNEE','WAREHOUSE_KEEPER','TRANSPORTER','AGENT'
  pary_id /fk excise_parties

excise_warehouses
  warehouse_id /pk
  warehouse_code vc255
  approval_number vc255 /index
  location_id /fk excise_locations
  operator_party_id /fk excise_parties

excise_event_warehouses
  event_warehouse_id /pk
  event_id /fk excise_events
  warehouse_id /fk excise_warehouses

excise_movements
  movement_id /pk
  event_id /nn /unique /fk excise_events
  movement_type vc255 /nn /check 'SUSPENSION','DUTY_PAID','EXPORT','IMPORT','TRANSFER'
  dispatch_location_id /fk excise_locations
  dispatch_ts timestamp
  destination_location_id /fk excise_locations
  expected_arrival_ts timestamp
  transport_mode vc255 /check 'ROAD','RAIL','SEA','AIR','INLAND_WATERWAY','COURIER','OTHER'
  vehicle_id vc255
  container_id vc255
  extensions clob /default {} /nn

excise_movement_references
  movement_reference_id /pk
  movement_id /fk excise_movements
  ref_type vc255 /nn    /check 'ARC','EAD','LOCAL_REFERENCE','CUSTOMS_DECLARATION','OTHER'
  ref_value vc255 /nn

excise_movement_seals
  movement_seal_id /pk
  movement_id /fk excise_movements
  seal_number vc255 /nn

excise_items
  item_id /pk
  event_id /fk excise_events
  category vc255 /nn /check 'ALCOHOL','TOBACCO','ENERGY','OTHER'
  sub_category vc255
  excise_product_code vc255 /index
  commodity_code vc255
  description /nn
  brand vc255
  qty_amount num /nn
  qty_unit vc30 /nn
  origin_country_code vc2
  customs_value num
  transaction_value num
  extensions clob /default {} /nn

excise_item_strength
  item_strength_id /pk
  item_id /fk excise_items
  abv_percent num
  plato num
  api_gravity num
  litres_of _pure_alcohol num

excise_item_packaging
  item_packaging_id /pk
  item_id /fk excise_items
  package_type vc255 /nn
  units_per_package num
  package_count num
  net_content_amount num
  net_content_unit vc30
  
excise_item_relief
  item_relief_id /pk
  item_id /fk excise_items
  relief_type vc255 /nn
  relief_reference vc255
  relief_amount num
  extensions clob /default {} /nn

excise_tax_calculations
  tax_calc_id /pk
  event_id /fk excise_events /nn /unique
  currency vc3 /nn
  calculation_method vc200
  excise_duty_total num /nn
  other_tax_total num /nn
  grand_total num /nn

excise_tax_lines
  tax_line_id /pk
  tax_calc_id /fk excise_tax_calculations /nn
  item_id /fk excise_items
  tax_type vc30 /nn /check 'EXCISE_DUTY','ENVIRONMENTAL_LEVY','OTHER'
  rate_amount num /nn
  rate_basis vc255 /nn
  taxable_qty_amount num /nn
  taxable_qty_unit vc50 /nn
  relief_applied num /nn /default 0
  tax_amount num /nn
  calculation_notes
  extensions clob /default {} /nn

excise_evidence
  evidence_id /pk
  event_id /fk excise_events
  evidence_type vc40 /nn /check 'COMMERCIAL_INVOICE','TRANSPORT_DOCUMENT','WAREHOUSE_RECORD','LAB_CERTIFICATE','CUSTOMS_DECLARATION','LOSS_REPORT','DESTROY_CERTIFICATE','OTHER'
  reference vc255 /nn
  issued_by vc255
  issued_date date
  uri
  evidence file

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","db":"23","drop":"Y","pk":"IDENTITY"}

*/