create table fac_di_access_control (
    id                             number generated by default on null as identity 
                                   constraint fac_di_access_cont_id_pk primary key,
    user_name                      varchar2(255 char) not null,
    entity_type                    varchar2(255 char) not null,
    entity_id                      number not null,
    direction                      varchar2(4000 char) not null,
    enabled_flag                   varchar2(1 char) default 'Y',
    start_date_active              date default SYSDATE,
    end_date_active                date,
    deletion_date                  date,
    attribute_context              varchar2(4000 char),
    attribute_01                   varchar2(255 char),
    attribute_02                   varchar2(255 char),
    attribute_03                   varchar2(255 char),
    attribute_04                   varchar2(4000 char),
    attribute_05                   varchar2(4000 char),
    n_attribute_01                 number,
    n_attribute_02                 number,
    d_attribute_01                 date,
    d_attribute_02                 date,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;