create table fac_di_report_categories (
    id                             number generated by default on null as identity 
                                   constraint fac_di_report_cate_id_pk primary key,
    parent_category_id             number
                                   constraint fac_di_report_parent_catego_fk
                                   references fac_di_report_categories,
    category_code                  varchar2(100 char),
    category_name                  varchar2(150 char)
                                   constraint fac_di_report_c_category_n_unq unique not null,
    description                    varchar2(240 char),
    start_date_active              date default SYSDATE,
    end_date_active                date,
    enabled_flag                   varchar2(1 char) default 'Y',
    seeded_flag                    varchar2(1 char) default 'N',
    apex_icon                      varchar2(255 char),
    img_url                        varchar2(4000 char),
    display_seq                    varchar2(150 char),
    deletion_date                  date,
    attribute_context              varchar2(4000 char),
    attribute_01                   varchar2(255 char),
    attribute_02                   varchar2(255 char),
    attribute_03                   varchar2(255 char),
    attribute_04                   varchar2(4000 char),
    attribute_05                   varchar2(4000 char),
    n_attribute_01                 number,
    n_attribute_02                 number,
    d_attribute_01                 date,
    d_attribute_02                 date,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;