create or replace view fac_di_reports_v as
select r.id,
       a.id report_area_id,
       a.category_code report_area_code,
       a.category_name report_area,
       r.category_id,
       c.category_name,
       r.report_name,
       r.report_alias,
       r.version,
       r.description,
       r.apex_app_alias,
       r.apex_page_alias,
       r.status,
       r.start_date_active,
       r.end_date_active,
       r.enabled_flag,
       r.seeded_flag,
       nvl(nvl(r.apex_icon,c.apex_icon),a.apex_icon) apex_icon,
       nvl(nvl(r.img_url,c.img_url),a.img_url) img_url,
       r.display_seq,
       r.deletion_date,
       r.attribute_context,
       r.attribute_01,
       r.attribute_02,
       r.attribute_03,
       r.attribute_04,
       r.attribute_05,
       r.n_attribute_01,
       r.n_attribute_02,
       r.d_attribute_01,
       r.d_attribute_02,
       r.created,
       r.created_by,
       r.updated,
       r.updated_by       
  from fac_di_reports r,
       fac_di_report_categories c,
       fac_di_report_categories a
 where r.category_id = c.id
   and c.parent_category_id = a.id
  ;