create table fac_di_favorites (
    id                             number generated by default on null as identity 
                                   constraint fac_di_favorites_id_pk primary key,
    username                      varchar2(255 char) not null,
    report_alias                  varchar2(255 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;