create or replace view fac_di_report_categories_v as
select c.id,
       c.parent_category_id,
       a.report_area_code,
       a.report_area,
	   c.category_code,
       c.category_name,
       c.description,
       c.start_date_active,
       c.end_date_active,
       c.enabled_flag,
       c.seeded_flag,
       nvl(c.apex_icon,a.apex_icon) apex_icon,
       nvl(c.img_url,a.img_url) img_url,
       c.display_seq,
       c.deletion_date,
       c.attribute_context,
       c.attribute_01,
       c.attribute_02,
       c.attribute_03,
       c.attribute_04,
       c.attribute_05,
       c.n_attribute_01,
       c.n_attribute_02,
       c.d_attribute_01,
       c.d_attribute_02,
       c.created,
       c.created_by,
       c.updated,
       c.updated_by
  from fac_di_report_categories c,
       fac_di_report_areas_v a
 where c.parent_category_id = a.id;