-- +==============================================================================================+
-- |                                                                                              |
-- |                            (c) Fujitsu Services Ltd (2022)                                   |
-- |                                                                                              |
-- |                                      Fujitsu FACES   - Reachback                             |
-- |                                                                                              |
-- +==============================================================================================+
-- |                                                                                              |  
-- | Change Record:                                                                               |
-- | ==============                                                                               |
-- | Version   Date         Author           Remarks                                              |
-- | =======   ===========  =============    =====================================================|
-- | 1.0       30/09/2022   Rashmi Mishra    Initial Version -- |                                 |
-- ============================================================================================== +
--

-- drop objects
-- New config table for Reachback
--drop table rb_configuration cascade constraints; -- contains URL info
--drop table rb_users cascade constraints; -- Users 

-- create tables
create table rb_configuration (
    id                             number generated by default on null as identity 
                                   constraint rb_configuration_id_pk primary key,
    row_version                    integer not null,
    config_key                     varchar2(255 char) not null,
	config_value                   varchar2(512 char) not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- comments
comment on table rb_configuration is 'Controls the url for the Reachback solution';
 
-- triggers
create or replace trigger rb_configuration_biu
    before insert or update 
    on rb_configuration
    for each row
begin
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end rb_configuration_biu;
/
