-- +==============================================================================================+
-- |                                                                                              |
-- |                                                                                              |
-- |                                      Fujitsu FACES   - Reachback                             |
-- |                                                                                              |
-- +==============================================================================================+
-- |                                                                                              |  
-- | Change Record:                                                                               |
-- | ==============                                                                               |
-- | Version   Date         Author           Remarks                                              |
-- | =======   ===========  =============    =====================================================|
-- | 1.0       30/09/2022   Rashmi Mishra    Initial Version 
-- |                                                                                              |
-- ============================================================================================== +
--


-- create tables

create table rb_users (
    id                             number generated by default on null as identity 
                                   constraint rb_users_id_pk primary key,
    row_version                    integer not null,
    username                       varchar2(100 char) not null,
    first_name                     varchar2(100 char),
    last_name                      varchar2(100 char),
    email                          varchar2(100 char) not null,
    job_title                      varchar2(100 char),
    --is_activated                   varchar2(1) default 'N' not null,
    last_login                     date,
    user_image                     blob,
    user_image_filename            varchar2(512 char),
    user_image_mimetype            varchar2(512 char),
    user_image_charset             varchar2(512 char),
    user_image_lastupd             date,
    enabled_flag                   varchar2(2 char) default 'Y' not null,
    created                        date not null,
    created_by                     varchar2(255 char) not null,
    updated                        date not null,
    updated_by                     varchar2(255 char) not null
)
;

-- comments
comment on column rb_users.email is 'Specifies the email address for use with general correspondence, notifications about resetting passwords, etc.';
comment on column rb_users.enabled_flag is 'Indicates whether the user is enabled to access the application';
comment on column rb_users.first_name is 'Specify the first or given name to further identify the user. This optional field is used for informational purposes only.';
comment on column rb_users.job_title is 'The job title of the user of the application';
comment on column rb_users.last_name is 'Specify the last or family name to further identify the user. This optional field is used for informational purposes only.';
comment on column rb_users.username is 'Specifies the username used to log in to the system. Usernames have these restrictions: maximum length of 100 characters, no spaces, only these special characters are permitted: @ and periods (.)  The username may also be used to reference user activity using the monitor applications. The bind variable :app_user returns the value of the current user when building applications.';


-- triggers

create or replace trigger rb_users_biu
    before insert or update 
    on rb_users
    for each row
begin
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end rb_users_biu;
/
